### ISSUE TITLE
Some Modification to Code

### ISSUE THREAD

**Issue by mfuphi** [andreatramacere/jetset-installer#1]
Hi @andreatramacere ,

I want to use a csv data file that has many more headings than the predefined ecsv format in jetset.data_loader.py. Is it possible for me to edit this code to handle more headings?

I have modified the
**self._names**,
**self._dt** and
**self._units**
variables. It looks like I may have to make more modifications, like on the 
**_check_frame_and_scale()**,
**from_asdc()**,
**_build_empty_table()**,
**_build_data()**,
**_set_data_frame_and_scale()**,
 methods.

Is this a good idea? What are your thoughts/suggestions?

**Comment by andreatramacere** [comment]
Hi @mfuphi , could you please open this issue in the jetset repo https://github.com/andreatramacere/jetset,
and also propose the modification with the lines number, plus a .ecsv file to test it?
Thanks
